### ISSUE TITLE
P2P

### ISSUE THREAD

**Issue by AbdelrhmanAmin** [vichuge/4-Building-with-Backgrounds-and-Gradients#2]
To place the search icon inside the search input:
The div container: 
.inner-addon{
position:relative;
}

the search icon:
.give the icon a class{
position:absolute;
left:30px;
top:3px;
}

**Comment by VanessaAoki** [comment]
Hey guys! This is a beautiful project, congratulations!

I have one little suggestion, on the 4 images grid, might be easier to add the images on the html file instead of using backgrounds (I know that this project is supposed to use backgrounds, just a suggestion for the next ones).
You could simply do grid-template-column: repeat (4, auto); set a width and the images would probably fit!

Keep up the good work!
